### ISSUE TITLE
Naming not aligned

### ISSUE THREAD

**Issue by michbin** [openBackhaul/vlanInterface#11]
The names of some Yang model elements are not aligned with the corresponding names of other models:

- `vlan-interface-current-problem`
- `vlan-interface-historical-performance`
(although this name is in line with `vlan-interface-current-performance` which may also contain more than 1 data set)

**Comment by openBackhaul** [comment]
Many thanks for indicating at such an early stage.
Issue has been corrected with VlanInterface_1.0.0-tsp.200731.1235+yang.2 .
