### ISSUE TITLE
Insufficient size of VLAN IDs

### ISSUE THREAD

**Issue by michbin** [openBackhaul/vlanInterface#13]
Various attributes which represent VLAN IDs have an insufficient size (`int8`). Examples:
- `external-vlan-id`
- `internal-vlan-id`
- `egress-vlan-id`
- `forwarded-vlan-id-list`

**Comment by openBackhaul** [comment]
**Proposal:**
It is proposed to change the following attributes from int8 to the respective Integer size:

`ExternalToInternalVlanIdMappingType::external-vlan-id : INT16`
`ExternalToInternalVlanIdMappingType::internal-vlan-id : INT16` 

`InternalToEgressVlanIdMappingType::internal-vlan-id : INT16`
`InternalToEgressVlanIdMappingType::egress-vlan-id : INT16`

`ForwardedProtocolVlanIdGroupingType::forwarded-vlan-id-list : INT64`

**Comment by demx8as6** [comment]
2010-10-21: Agreed as proposed.

**Comment by demx8as6** [comment]
YANGs seems to be updated already - if UML is also ok, then issue should be closed.
