### ISSUE TITLE
VlanInterface_1.0.0-tsp.200731.1235+yang.3 compilation issues

### ISSUE THREAD

**Issue by alexandrustancu** [openBackhaul/vlanInterface#14]
VlanInterface_1.0.0-tsp.200731.1235+yang.3 yang model has compilation issues:

└─ $ ▶ pyang vlan-interface-1-0.yang 
vlan-interface-1-0.yang:1: error: syntax error: illegal keyword: ﻿module vlan-interface-1-0 {

Probable cause: file was edited manually under Windows.

Solution: using the **dos2unix** tool under linux:
└─ $ ▶ dos2unix -o vlan-interface-1-0.yang

**Comment by michbin** [comment]
The problem was caused by the BOM (byte-order mark) at the beginning of the file. It is not shown by most editors.
Some editors (e.g. Notepad++) allow to choose UTF-8 encoding with or without BOM.
