### ISSUE TITLE
Removing all elements related to Alarms

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanInterface#15]
Because Alarms require several objects and many attributes, but provide (almost) no benefit at the VlanInterface, it is proposed to delete the following elements from the modeling:
-	VlanInterfaceCapability::supportedAlarmList attribute
-	VlanInterfaceConfiguration::problemKindSeverityList attribute
-	ProblemKindSeverityType datatype
-	SeverityType enumeration
-	VlanInterface_Pac::_VlanInterfaceCurrentProblems attribute
-	VlanInterfaceCurrentProblems class
-	VlanInterfaceCurrentProblemType datatype
-	CurrentProblem datatype

**Comment by demx8as6** [comment]
2020-10-21: Agreed as proposed!
