### ISSUE TITLE
Deleting VlanInterfaceConfiguration::InterfaceIsOn

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanInterface#16]
The VlanInterfaceConfiguration::InterfaceIsOn attribute is not supported by almost all devices.
The interface could also be switched by an InterfaceIsOn attribute at an underlying layer (e.g. EthernetContainer or WireInterface).

It is proposed to delete the VlanInterfaceConfiguration::InterfaceIsOn attribute.

**Comment by demx8as6** [comment]
2020-10-21: Agreed as proposed!
