### ISSUE TITLE
Removing all elements related to Performance Values

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanInterface#21]
It turned out that the Performance Values listed by vendors in the Supported Attributes Inquiry at the VlanInterface are identical with the ones provided with the MacInterface.

So, no vendor feedback indicated Performance Values specific to the VlanInterface.

As a consequence, it is proposed to delete the following elements from the modeling:
VlanInterfaceCapability::performanceMonitoringIsAvail attribute
VlanInterfaceConfiguration::performanceMonitoringIsOn attribute
VlanInterface_Pac::_vlanInterfaceCurrentPerformance attribute
VlanInterfaceCurrentPerformance class
VlanInterfaceCurrentPerformanceType datatype
CurrentPerformance class
GranularityPeriodType enumeration
VlanInterfacePerformanceType datatype
VlanInterface_Pac::_vlanInterfaceHistoricalPerformance attribute
VlanInterfaceHistoricalPerformances class
VlanInterfaceHistoricalPerformanceType datatype
HistoricalPerformance class

**Comment by demx8as6** [comment]
2020-10-21: Agreement: go with the proposal!
