### ISSUE TITLE
Deleting VlanInterfaceConfiguration::maintenanceTimer

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanInterface#22]
The VlanInterfaceConfiguration::maintenanceTimer attribute is not supported by any of the analysed devices.

It is proposed to delete the VlanInterfaceConfiguration::maintenanceTimer attribute.

**Comment by demx8as6** [comment]
2020-10-21: Agreed as proposed!

**Comment by openBackhaul** [comment]
Deleted the corresponding Capability attribute, too
