### ISSUE TITLE
Removing all elements related to Loop Back

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanInterface#23]
It turned out that none of the devices analysed in the Supported Attributes Inquiry is supporting Loop Back on the VLAN interface level (but on lower OSI layers).

As a consequence, it is proposed to delete the following elements from the modeling:
- VlanInterfaceCapability::supportedLoopBackKindList attribute
- LoopBackType enumeration
- VlanInterfaceConfiguration::loopBackKindOn attribute
- VlanInterfaceConfigurationStatus::loopBackKindUp attribute

**Comment by demx8as6** [comment]
2020-10-21: Agreed as proposed
by Yossi: relation to mac, but ok to remove from VlanInterface
