### ISSUE TITLE
historical-performance-data -> historical-performance-data-list

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/vlanInterface#24]
Proposal:
To align with general naming practice, the name of the historical-performance-data attribute shall be changed towards historical-performance-data-list.

**Comment by demx8as6** [comment]
historical-performance-data  -> goes to  historical-performance-data**-list**
as for all other interfaces

2020-12-09: decided as proposed.

**Comment by openBackhaul** [comment]
Issue obsolete, because attribute deleted according to #21 .
